//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prism.Autofac.Perspex.Android.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prism.Autofac.Perspex.Android.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper sequence completed..
        /// </summary>
        internal static string BootstrapperSequenceCompleted {
            get {
                return ResourceManager.GetString("BootstrapperSequenceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring the Autofac container builder..
        /// </summary>
        internal static string ConfiguringAutofacContainerBuilder {
            get {
                return ResourceManager.GetString("ConfiguringAutofacContainerBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring ServiceLocator singleton..
        /// </summary>
        internal static string ConfiguringServiceLocatorSingleton {
            get {
                return ResourceManager.GetString("ConfiguringServiceLocatorSingleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring the ViewModelLocator to use Autofac..
        /// </summary>
        internal static string ConfiguringViewModelLocator {
            get {
                return ResourceManager.GetString("ConfiguringViewModelLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Autofac container..
        /// </summary>
        internal static string CreatingAutofacContainer {
            get {
                return ResourceManager.GetString("CreatingAutofacContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Autofac container builder..
        /// </summary>
        internal static string CreatingAutofacContainerBuilder {
            get {
                return ResourceManager.GetString("CreatingAutofacContainerBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the page..
        /// </summary>
        internal static string CreatingPage {
            get {
                return ResourceManager.GetString("CreatingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing the page..
        /// </summary>
        internal static string InitializingPage {
            get {
                return ResourceManager.GetString("InitializingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger was created successfully..
        /// </summary>
        internal static string LoggerCreatedSuccessfully {
            get {
                return ResourceManager.GetString("LoggerCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ContainerBuilder is required and cannot be null..
        /// </summary>
        internal static string NullAutofacContainerBuilderException {
            get {
                return ResourceManager.GetString("NullAutofacContainerBuilderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IContainer is required and cannot be null..
        /// </summary>
        internal static string NullAutofacContainerException {
            get {
                return ResourceManager.GetString("NullAutofacContainerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ILoggerFacade is required and cannot be null..
        /// </summary>
        internal static string NullLoggerFacadeException {
            get {
                return ResourceManager.GetString("NullLoggerFacadeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering Framework Exception Types..
        /// </summary>
        internal static string RegisteringFrameworkExceptionTypes {
            get {
                return ResourceManager.GetString("RegisteringFrameworkExceptionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; was already registered by the application. Skipping....
        /// </summary>
        internal static string TypeMappingAlreadyRegistered {
            get {
                return ResourceManager.GetString("TypeMappingAlreadyRegistered", resourceCulture);
            }
        }
    }
}
